Repository codalab/codalab-worksheets, pull requests merged in 2019-11, with the labels that each got.

#1579 Bundle bulk operation on web ui
  frontend/src/components/worksheets/BundleBulkActionMenu.js
  frontend/src/components/worksheets/Worksheet.js
  frontend/src/components/worksheets/WorksheetDialogs.js
  frontend/src/components/worksheets/WorksheetHeader.js
  frontend/src/components/worksheets/WorksheetItemList.js
  frontend/src/components/worksheets/items/ActionButtons.js
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: frontend

#1599 Don't push docker images on PR builds
  .travis.yml
Labels: WIP DO NOT MERGE

#1631 Refactor bundle_manager.py to have less db call and reuse some variables
  codalab/server/bundle_manager.py
Labels: backend
