Repository codalab/codalab-worksheets, pull requests merged in 2020-09, with the labels that each got.

#2767 Set timeouts for urlopen calls
  codalab/common.py
  codalab/lib/file_util.py
  codalab/server/auth.py
  codalab/worker/bundle_service_client.py
  codalab/worker/rest_client.py
Labels: ready-to-merge

#2764 Add pre-commit.sh to the test.yml
  .github/workflows/test.yml
  docs/CLI-Reference.md
  pre-commit.sh
Labels: ready-to-merge

#2759 Some more conversions of logger.error to logger.warning
  codalab/worker/worker.py
Labels: ready-to-merge

#2818 Update Interactive Session edit commands instructions
  codalab/lib/interactive_session.py
Labels: ready-to-merge

#2775 Avoid conflicting worker resources
  codalab/server/bundle_manager.py
  stress_test.py
Labels: backend, bug, python

#2834 Fix issue 2617 by removing redundant href
  frontend/src/components/worksheets/items/WorksheetItem.js
Labels: ready-to-merge

#2735 Validate new worksheet name on frontend
  frontend/src/components/NavBar.js
  frontend/src/components/worksheets/NewWorksheet.js
  frontend/src/constants.js
Labels: ready-to-merge

#2835 Provide sticky header for result tables
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: feature, frontend, ready-to-merge

#2850 Add staged_status to bundle details page
  frontend/src/components/worksheets/BundleDetail/BundleDetailSideBar.jsx
Labels: frontend, ready-to-merge

#2762 switch shift-enter and enter in New Run logic change
  frontend/src/components/worksheets/NewRun/NewRun.jsx
Labels: ready-to-merge

#2733 Create an indicator for when the cursor is "above" all bundles
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#2851 Update frontend test snapshot
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
Labels: ready-to-merge

#2463 Share workers among group members
  .github/workflows/test.yml
  alembic/versions/2020081018_added_group_uuid_to_worker_9d3ab0b9d304.py
  codalab/lib/bundle_cli.py
  codalab/model/bundle_model.py
  codalab/model/tables.py
  codalab/model/worker_model.py
  codalab/objects/permission.py
  codalab/rest/workers.py
  codalab/server/bundle_manager.py
  codalab/server/worker_info_accessor.py
  codalab/worker/main.py
  codalab/worker/worker.py
  docs/Execution.md
  tests/cli/test_cli.py
Labels: ready-to-merge

#2867 Fix the bug of upload not releasing keyboard shortcuts
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: bug, frontend, ready-to-merge

#2866 Remove componentWillMount and componentWillReceiveProps in FileBrowser
  frontend/src/components/FileBrowser/FileBrowser.js
Labels: frontend, health, ready-to-merge

#2876 Move jump-to-end button to front
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#2883 Make file browser have less vertical spacing
  frontend/src/components/FileBrowser/FileBrowser.js
Labels: frontend

#2884 Update dummy header id for consistency
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#2879 Better style of bundle table header
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: frontend, ready-to-merge

#2766 Remove "CREATED" docker containers when they've failed to start
  codalab/worker/docker_utils.py
Labels: ready-to-merge

#2895 Make WorkerManager name subparser required
  codalab/worker_manager/main.py
Labels: ready-to-merge

#2894 Put the hostname in the remote: field for workermanager-launched jobs
  codalab/worker_manager/worker_manager.py
  tests/unit/worker_manager/slurm_batch_worker_manager_test.py
Labels: ready-to-merge
