Repository codalab/codalab-worksheets, pull requests merged in 2020-10, with the labels that each got.

#2686 Add schema button and delete schema button
  codalab/lib/worksheet_util.py
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/Worksheet/WorksheetHeader.js
  frontend/src/components/worksheets/WorksheetItemList.js
  frontend/src/components/worksheets/items/ActionButtons.js
  frontend/src/components/worksheets/items/ItemWrapper.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: ready-to-merge

#2912 Fix frontend npm build warnings
  frontend/.eslintrc.json
  frontend/src/CodalabApp.js
  frontend/src/__tests__/Worksheet.test.js
  frontend/src/components/Button.js
  frontend/src/components/FileBrowser/FileBrowser.js
  frontend/src/components/Login.js
  frontend/src/components/UserInfo.js
  frontend/src/components/worksheets/BundleBulkActionMenu.js
  frontend/src/components/worksheets/ErrorMessage.js
  frontend/src/components/worksheets/NewWorksheet.js
  frontend/src/components/worksheets/RunBundleBuilder.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/items/ContentsItem.js
  frontend/src/components/worksheets/items/GraphItem.js
  frontend/src/components/worksheets/items/MarkdownItem.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
  frontend/src/components/worksheets/items/TextEditorItem/TextEditorItem.js
  frontend/src/components/worksheets/items/WorksheetItem.js
  frontend/src/css/imports.scss
  frontend/src/util/worksheet_utils.js
  tests/ui/ui_tester.py
Labels: frontend, health, ready-to-merge

#2697 Reset the state rows when opening the schema detail
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: ready-to-merge

#2907 Remove scrollbar in table
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: frontend

#2916 Remove dependabot.yml
  .github/dependabot.yml
Labels: ready-to-merge

#2925 Fix the bug of window unexpectedly scrolling to the table center
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#2944 Fix AWsBatchWorkerManager --job-filter
  codalab/worker_manager/aws_batch_worker_manager.py
Labels: ready-to-merge

#2956 Run github actions on all PRs, even those that are not to master
  .github/workflows/test.yml
Labels: ready-to-merge

#2911 Fix 'j k' keyboard shortcut for scroll up and down
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: frontend, ready-to-merge

#2943 Remove extra space between the navbar and the homepage
  frontend/src/routes/HomePage.js
Labels: ready-to-merge

#2954 order search results by user's own worksheets
  codalab/lib/bundle_cli.py
  codalab/model/bundle_model.py
  docs/CLI-Reference.md
Labels: ready-to-merge

#2923 Provide an adaptive text wrap for the first column in the table
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
Labels: ready-to-merge

#2897 Make AWSBatchWorkerManager boto3 warning stricter and more robust
  codalab/worker_manager/aws_batch_worker_manager.py
  requirements-server.txt
Labels: ready-to-merge

#2941 Better style of the schema blocks
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/items/ItemWrapper.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: ready-to-merge

#2389 `uls` search for user stats
  codalab/lib/bundle_cli.py
  codalab/model/bundle_model.py
  codalab/rest/bundles.py
  codalab/rest/groups.py
  codalab/rest/users.py
  codalab/rest/worksheets.py
  docs/CLI-Reference.md
  docs/REST-API-Reference.md
  tests/cli/test_cli.py
Labels: backend, feature, python, ready-to-merge

#2952 Apache Beam, file_util and zip_util changes needed for Azure Blob Storage
  codalab/lib/zip_util.py
  codalab/worker/file_util.py
  docker/dockerfiles/Dockerfile.server
  docker/dockerfiles/Dockerfile.worker
  requirements-server.txt
  requirements.txt
  setup.cfg
  tests/cli/test_cli.py
  tests/unit/worker/file_util_test.py
Labels: ready-to-merge

#2953 Add upload-download tests
  tests/unit/server/bundle_manager/__init__.py
  tests/unit/server/upload_download_test.py
Labels: ready-to-merge

#2955 Set up Azurite and Azure connection
  codalab/lib/beam/__init__.py
  codalab/lib/beam/filesystems.py
  codalab_service.py
  docker/compose_files/docker-compose.yml
  requirements.txt
  scripts/initialize-azurite.py
  setup.cfg
Labels: ready-to-merge

#2984 Fix flake8 issues
  codalab/lib/beam/filesystems.py
  codalab/lib/bundle_cli.py
  codalab/lib/zip_util.py
  codalab/model/bundle_model.py
  codalab/rest/workers.py
  codalab/worker/file_util.py
  codalab_service.py
  scripts/initialize-azurite.py
  tests/unit/server/bundle_manager/__init__.py
  tests/unit/server/upload_download_test.py
Labels: ready-to-merge

#2979 Provide a keyboard shortcut to exit schema editor
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
  frontend/src/constants.js
Labels: ready-to-merge

#2980 Fix keyboard shortcut bug
  frontend/src/components/worksheets/items/WorksheetItem.js
Labels: ready-to-merge

#2964 Fix frontend scrolling issue
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/BundleDetail/BundleDetail.jsx
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/WorksheetDialogs.js
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
Labels: ready-to-merge

#2968 Copy over BlobStorageFileSystem code from Apache Beam
  codalab/lib/beam/blobstoragefilesystem.py
  codalab/lib/beam/blobstorageio.py
  codalab/lib/beam/filesystems.py
  codalab_service.py
  pyproject.toml
  setup.cfg
  tests/unit/server/upload_download_test.py
Labels: ready-to-merge

#2989 No auto close for the schema editor; No '_' when hitting "enter".
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: ready-to-merge

#2991 Keep all other fields intact and clear only the password field when the user fails in the sign up process
  frontend/src/components/SignUp.js
Labels: ready-to-merge

#2998 Change urlopen timeout from 30 to 120 seconds
  codalab/common.py
Labels: ready-to-merge

#2983 Add required CI check for when all CI tasks are complete
  .github/workflows/test.yml
Labels: ready-to-merge
