Repository codalab/codalab-worksheets, pull requests merged in 2021-04, with the labels that each got.

#3372 Fix target sizes for directories -- return data_size if user requests the whole bundle
  codalab/rest/bundles.py
Labels: ready-to-merge

#3353 Use useSWR as a cache for the search directive
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/worksheets/items/PlaceholderItem.js
Labels: ready-to-merge

#3375 change link mount to read only
  .github/workflows/test.yml
  codalab_service.py
  docs/Server-Setup.md
  tests/cli/test_cli.py
  tests/test-setup.sh
Labels: backend, ready-to-merge

#3386 Docs: clarify that you can run different tests using test_runner.py
  docs/Code-Overview.md
Labels: documentation, ready-to-merge

#3279 Add Quickstart Example Documentation
  docs/examples/quickstart.md
  docs/images/quickstart/add-worksheet.png
  docs/images/quickstart/bundle-detail.png
  docs/images/quickstart/data-code.png
  docs/images/quickstart/edit-avatar.png
  docs/images/quickstart/profile.png
  docs/images/quickstart/run-python.png
  mkdocs.yml
Labels: blocked

#3399 Fix the bug of rerun bundle inserting to wrong position
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
Labels: ready-to-merge

#3390 Fix LATEX rendering bug
  frontend/src/components/worksheets/items/MarkdownItem.js
Labels: ready-to-merge

#3318 Enable freezing and unfreezing bundles
  .github/workflows/test.yml
  alembic/versions/2021022802_add_frozen_field_to_bundle_6c013a88862f.py
  codalab/bundles/private_bundle.py
  codalab/lib/bundle_cli.py
  codalab/lib/bundle_util.py
  codalab/model/tables.py
  codalab/objects/bundle.py
  codalab/rest/bundles.py
  codalab/rest/schemas.py
  codalab/worker/bundle_state.py
  docs/CLI-Reference.md
  docs/REST-API-Reference.md
  docs/features/bundles/uploading.md
  tests/cli/test_cli.py
  tests/unit/objects/bundle_test.py
  tests/unit/rest/bundles_test.py
  tests/unit/rest/util_test.py
  tests/unit/server/bundle_manager/__init__.py
  tests/unit/worker/bundle_state_test.py
Labels: ready-to-merge

#3257 Store tracebacks in bundle metadata and send them to sentry
  codalab/bundles/named_bundle.py
  codalab/lib/worksheet_util.py
  codalab/objects/metadata_spec.py
  codalab/rest/bundles.py
  codalab/server/bundle_manager.py
  codalab/worker/dependency_manager.py
  codalab/worker/docker_image_manager.py
Labels: ready-to-merge

#3379 enforce disk quota on bundle uploads
  codalab/common.py
  codalab/lib/bundle_cli.py
  tests/cli/test_cli.py
Labels: ready-to-merge

#3398 Fix inconsistency update bug for the partial update mechanism
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#3413 Use shallow clones for git, for speed
  codalab/lib/file_util.py
Labels: ready-to-merge

#3309 Blob Storage: add download_util changes
  codalab/lib/beam/mockblobstoragefilesystem.py
  codalab/server/bundle_manager.py
  codalab/worker/download_util.py
  codalab/worker/file_util.py
  codalab/worker/tar_file_stream.py
  codalab/worker/tar_subdir_stream.py
  codalab/worker/un_gzip_stream.py
  setup.cfg
  tests/unit/worker/download_util_test.py
  tests/unit/worker/file_util_test.py
Labels: blob-storage

#3412 Simplify uploads by removing local path support
  codalab/lib/path_util.py
  codalab/lib/upload_manager.py
  codalab/objects/bundle.py
  codalab/rest/bundles.py
  tests/cli/test_cli.py
  tests/unit/lib/upload_manager_test.py
  tests/unit/server/upload_download_test.py
Labels: blob-storage, ready-to-merge

#3448 Fix the bug of cannot go back to profile page after visiting dashboard
  frontend/src/components/VerifySuccess.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/WorksheetNameSearch.js
Labels: ready-to-merge

#3432 Remove support for uploads of multiple URLs
  codalab/lib/bundle_cli.py
  codalab/lib/upload_manager.py
  codalab/rest/bundles.py
  docs/CLI-Reference.md
  docs/REST-API-Reference.md
  tests/cli/test_cli.py
  tests/unit/lib/upload_manager_test.py
  tests/unit/server/upload_download_test.py
Labels: blob-storage, breaking-change, ready-to-merge

#3419 Apply useSwr to FileBrowserLite and BundleDetail for previewing bundles
  frontend/src/components/FileBrowser/FileBrowser.js
  frontend/src/components/worksheets/BundleDetail/BundleDetail.jsx
  frontend/src/components/worksheets/BundleDetail/BundleDetailSideBar.jsx
Labels: ready-to-merge

#3450 Stop updating an invalid worksheet name in the frontend
  frontend/src/components/EditableField.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/Worksheet/WorksheetHeader.js
Labels: ready-to-merge

#3422 Add Tabs to MainPanel to show both Owned and Shared Worksheets
  frontend/src/components/Dashboard/MainPanel.js
  frontend/src/components/Dashboard/NewDashboard.js
Labels: ready-to-merge

#3449 Don't unpack from the bundle CLI when multiple archives are uploaded
  codalab/lib/zip_util.py
  tests/cli/test_cli.py
  tests/unit/lib/zip_util_test.py
Labels: blob-storage, breaking-change

#3400 A More Central Call for Ajax Calls
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Bundle/Bundle.js
  frontend/src/components/Dashboard/EditableAvatar.js
  frontend/src/components/Dashboard/MainPanel.js
  frontend/src/components/Dashboard/NewDashboard.js
  frontend/src/components/Dashboard/SideBar.js
  frontend/src/components/EditableField.js
  frontend/src/components/FileBrowser/FileBrowser.js
  frontend/src/components/NavBar.js
  frontend/src/components/UserInfo.js
  frontend/src/components/worksheets/BundleDetail/BundleActions.jsx
  frontend/src/components/worksheets/BundleDetail/BundleDetail.jsx
  frontend/src/components/worksheets/NewRun/NewRun.jsx
  frontend/src/components/worksheets/NewUpload/NewUpload.jsx
  frontend/src/components/worksheets/PermissionDialog.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/WorksheetTerminal.js
  frontend/src/components/worksheets/items/ImageEditor.js
  frontend/src/components/worksheets/items/MarkdownItem.js
  frontend/src/components/worksheets/items/RecordItem.js
  frontend/src/components/worksheets/items/TableItem/TableItem.js
  frontend/src/components/worksheets/items/TextEditorItem/TextEditorItem.js
  frontend/src/util/apiWrapper.js
  frontend/src/util/async_loading_utils.js
  frontend/src/util/cli_utils.js
Labels: ready-to-merge
