Repository codalab/codalab-worksheets, pull requests merged in 2021-02, with the labels that each got.

#3218 Fix none concatenation error when interpreting worksheet
  codalab/lib/worksheet_util.py
Labels: ready-to-merge

#3241 FIx the bug of `discard` button not closing the source editor
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#3147 Create a test for codalab service start
  .github/workflows/test.yml
  codalab_service.py
  tests/cli/test_cli.py
Labels: ready-to-merge

#3216 Bundle status refresh endpoint refreshes only the specified bundle
  codalab/rest/interpret.py
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  tests/unit/rest/worksheets_test.py
Labels: ready-to-merge

#3240 Add Avatar for Users
  alembic/versions/2021020207_add_avatar_db12798a7cf6.py
  codalab/model/bundle_model.py
  codalab/model/tables.py
  codalab/objects/user.py
  codalab/rest/schemas.py
  docs/REST-API-Reference.md
  docs/Server-Setup.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Dashboard/EditableAvatar.js
  frontend/src/components/Dashboard/NewDashboard.js
  frontend/src/components/Dashboard/SideBar.js
  frontend/src/components/worksheets/NewUpload/NewUpload.jsx
  tests/unit/objects/user_test.py
  tests/unit/rest/user_test.py
Labels: ready-to-merge

#3246 Update Competitions documentation
  docs/Competitions.md
Labels: ready-to-merge

#3244 Azure Blob part 1: Add MockBlobStorageFileSystem
  codalab/lib/beam/filesystems.py
  codalab/lib/beam/mockblobstoragefilesystem.py
  setup.cfg
  tests/unit/azure_blob_mock.py
Labels: ready-to-merge

#3250 Table cell render as 'Forbidden' instead of 'Loading...' when the user has no access
  codalab/rest/interpret.py
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
Labels: ready-to-merge

#3253 404 Page Not Showing HTML
  frontend/src/components/Bundle/Bundle.js
Labels: ready-to-merge

#3212 Speed up CLI by lazy loading some imports
  codalab/lib/bundle_cli.py
  codalab/lib/codalab_manager.py
  codalab/lib/completers.py
  codalab/lib/download_manager.py
  codalab/lib/upload_manager.py
  codalab/lib/zip_util.py
  codalab/worker/dependency_manager.py
  codalab/worker/file_util.py
  codalab/worker/rest_client.py
  codalab/worker/un_gzip_stream.py
  codalab/worker/un_tar_directory.py
  tests/unit/worker/file_util_test.py
Labels: ready-to-merge

#3262 Fix table in "Storage Externalization" section in docs
  docs/Externalization.md
Labels: documentation, ready-to-merge

#3271 Manually bind context to `this` for calllback function to solve "undefined" error
  frontend/src/components/Bundle/Bundle.js
Labels: ready-to-merge

#3297 v0.5.40
  codalab/common.py
  docs/REST-API-Reference.md
  frontend/src/constants.js
  setup.py
Labels: ready-to-merge

#3302 Unit test - don't expect a fixed time_quota / disk_quota
  tests/unit/rest/user_test.py
Labels: ready-to-merge

#3301 Fix test formatting, run black on all files
  pre-commit.sh
Labels: ready-to-merge

#3305 Blob Storage: Add --use-azure-blob-beta argument to bundle CLI
  codalab/lib/bundle_cli.py
  codalab/lib/upload_manager.py
  codalab/rest/bundles.py
  docs/CLI-Reference.md
  docs/REST-API-Reference.md
  tests/unit/lib/upload_manager_test.py
  tests/unit/server/upload_download_test.py
Labels: blob-storage, ready-to-merge

#3285 Fix "uploading results" error by sending data to keep the socket open
  codalab/lib/zip_util.py
  codalab/worker/rest_client.py
Labels: ready-to-merge

#3314 [Easy] Change the comment of AUTO_HIDDEN_DURATION
  frontend/src/constants.js
Labels: documentation

#3273 Add tutorial for uploading / downloading bundles
  docs/features/bundles/uploading.md
  docs/images/upload.png
  docs/images/uploaded.png
  mkdocs.yml
  requirements.docs.txt
Labels: documentation, ready-to-merge

#3313 Add checkbox to the delete worksheet dialog to prevent accidental deletion
  frontend/src/components/worksheets/WorksheetDialogs.js
Labels: frontend, ready-to-merge
