Repository codalab/codalab-worksheets, pull requests merged in 2021-06, with the labels that each got.

#3529 Remove jquery show and hide
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/FileBrowser/FileBrowser.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/Worksheet/Worksheet.scss
Labels: ready-to-merge

#3557 Optimize size of default-cpu / gpu dockerfiles, update to latest ubuntu and cuda, remove python 2
  .github/workflows/build_worker_images.yml
  docker_config/dockerfiles/Dockerfile.default-cpu
  docker_config/dockerfiles/Dockerfile.default-gpu
Labels: ready-to-merge

#3589 Fix Key Error in Competition Script
  scripts/competitiond.py
Labels: ready-to-merge

#3574 Multiline commands rendered with newlines in the bundle tables on a worksheet
  frontend/src/components/worksheets/BundleDetail/BundleDetailSideBar.jsx
Labels: ready-to-merge

#3612 Fix progress circle
  frontend/src/components/worksheets/NewUpload/NewUpload.jsx
Labels: ready-to-merge

#3610 Monitor: Show results of df in human-readable format
  monitor.py
Labels: ready-to-merge

#3613 Properly set finalize_on_failure=1 on file uploads from the web UI
  frontend/src/util/apiWrapper.js
Labels: frontend, ready-to-merge

#3611 Better logging when unzip or file uploads fail, fix zip file upload error
  codalab/rest/bundles.py
  codalab/worker/file_util.py
Labels: ready-to-merge

#3616 Eliminate delay for deleting bundles
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#3615 Fix bug of save shortcut for editing table headers
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: ready-to-merge

#3622 Revert "Monitor: Show results of df in human-readable format"
  monitor.py
Labels: ready-to-merge

#3617 Fix bug of cut & paste bundles
  frontend/src/components/worksheets/Worksheet/Worksheet.js
Labels: ready-to-merge

#3560 Fix Scrolling Issue
  frontend/src/components/worksheets/Worksheet/WorksheetHeader.js
  frontend/src/components/worksheets/items/TableItem/TableItem.js
  frontend/src/css/imports.scss
Labels: ready-to-merge

#3559 Make import error message more specific
  codalab/worker_manager/gcp_batch_worker_manager.py
Labels: ready-to-merge

#3533 Stricter Linting
  frontend/.babelrc
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChangeEmail.js
  frontend/src/components/FileBrowser/FileBrowser.js
  frontend/src/components/Login.js
  frontend/src/components/PasswordReset.js
  frontend/src/components/SignUp.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/items/MarkdownItem.js
  frontend/src/components/worksheets/items/RecordItem.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
  frontend/src/components/worksheets/items/TableItem/TableItem.js
  frontend/src/components/worksheets/items/TextEditorItem/TextEditorItem.js
  frontend/src/components/worksheets/items/WorksheetItem.js
  frontend/src/routes/HomePage.js
Labels: ready-to-merge

#3520 Blob Storage: fix dependency download for make bundles
  .github/workflows/test.yml
  codalab/lib/beam/mockblobstoragefilesystem.py
  codalab/server/bundle_manager.py
  codalab/worker/dependency_manager.py
  codalab/worker/file_util.py
  tests/unit/server/bundle_manager/make_bundles_test.py
  tests/unit/server/upload_download_test.py
  tests/unit/worker/file_util_test.py
Labels: blob-storage, ready-to-merge

#3549 Kubernetes Batch Worker Manager
  codalab/worker_manager/kubernetes_worker_manager.py
  codalab/worker_manager/main.py
  codalab_service.py
  docker_config/compose_files/docker-compose.yml
  requirements-server.txt
Labels: ready-to-merge

#3473 Implement multipart upload for Azure Blob Storage uploads
  codalab/lib/beam/blobstorageuploader.py
  codalab/lib/beam/filesystems.py
  setup.cfg
Labels: goal-blob-storage, ready-to-merge
