Repository codalab/codalab-worksheets, pull requests merged in 2021-05, with the labels that each got.

#3444 Fix sentry setup by including sentry environment variables in docker-compose.yml
  codalab/lib/telemetry_util.py
  codalab/server/rest_server.py
  codalab/worker_manager/aws_batch_worker_manager.py
  codalab/worker_manager/azure_batch_worker_manager.py
  codalab_service.py
  docker_config/compose_files/docker-compose.yml
Labels: ready-to-merge

#3434 Simplify uploads by extracting directly to bundle_path, streaming downloaded URLs
  codalab/lib/file_util.py
  codalab/lib/upload_manager.py
  codalab/lib/zip_util.py
  tests/unit/lib/upload_manager_test.py
Labels: blob-storage, ready-to-merge

#3435 Remove simplify_archive
  codalab/lib/bundle_cli.py
  codalab/lib/upload_manager.py
  codalab/lib/zip_util.py
  codalab/rest/bundles.py
  docs/REST-API-Reference.md
  tests/cli/test_cli.py
  tests/unit/lib/upload_manager_test.py
  tests/unit/lib/zip_util_test.py
  tests/unit/server/upload_download_test.py
Labels: blob-storage, breaking-change, ready-to-merge

#3454 Fix disk quota enforcement error for non-root users by using correct endpoint
  codalab/lib/bundle_cli.py
  tests/cli/test_cli.py
Labels: ready-to-merge

#3370 benchmark bundle stages
  codalab/bundles/run_bundle.py
  codalab/model/bundle_model.py
  codalab/worker/bundle_state.py
  codalab/worker/worker.py
  codalab/worker/worker_run_state.py
  tests/cli/test_cli.py
  tests/unit/server/bundle_manager/__init__.py
  tests/unit/server/bundle_manager/schedule_run_bundles_test.py
Labels: backend, ready-to-merge

#3482 Fix delete bundle issue
  frontend/src/components/Dashboard/MainPanel.js
  frontend/src/components/NavBar.js
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/WorksheetTerminal.js
  frontend/src/util/apiWrapper.js
Labels: ready-to-merge

#3463 Add CAPTCHA for Registration
  codalab/rest/account.py
  codalab_service.py
  docker_config/compose_files/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SignUp.js
  tests/unit/rest/account_test.py
Labels: ready-to-merge

#3501 Read Runtime Environment Variables for Frontend
  codalab_service.py
  docker_config/compose_files/docker-compose.dev.yml
  docker_config/compose_files/docker-compose.yml
  docker_config/dockerfiles/Dockerfile.frontend
  frontend/.gitignore
  frontend/public/index.html
  frontend/src/components/SignUp.js
  setup-frontend.js
Labels: ready-to-merge

#3272 Redo the stats of docker images
  codalab/bundles/run_bundle.py
  codalab/model/bundle_model.py
  codalab/worker/bundle_state.py
  codalab/worker/docker_utils.py
  codalab/worker/worker.py
  codalab/worker/worker_run_state.py
  tests/unit/server/bundle_manager/__init__.py
Labels: ready-to-merge

#3490 Remove unneeded Beam code from un_bz2_file
  codalab/worker/file_util.py
Labels: ready-to-merge

#3467 setup sentry for frontend
  codalab_service.py
  docker_config/compose_files/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
Labels: ready-to-merge

#3464 Fix Schema Deletion Bug
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: ready-to-merge

#3504 Catch Parsing Error of Datetime
  codalab/model/bundle_model.py
Labels: ready-to-merge

#3485 Make unpacking zip files streaming
  codalab/lib/beam/streamingzipfile.py
  codalab/lib/zip_util.py
  codalab/worker/file_util.py
  codalab/worker/un_gzip_stream.py
  codalab/worker/un_tar_directory.py
  setup.cfg
  tests/unit/beam/__init__.py
  tests/unit/beam/streamingzipfile_test.py
  tests/unit/lib/zip_util_test.py
  tests/unit/worker/file_util_test.py
Labels: blob-storage, ready-to-merge

#3489 Add zip_util.unpack_to_archive to unpack archives directly to a fileobj on Blob Storage
  codalab/lib/zip_util.py
  codalab/worker/un_gzip_stream.py
  tests/unit/lib/zip_util_test.py
  tests/unit/worker/file_util_test.py
Labels: blob-storage

#3524 Remove redundant space between nav bar and image/header below
  frontend/src/css/imports.scss
  frontend/src/routes/HomePage.js
Labels: ready-to-merge

#3496 Blob Storage Upload
  codalab/common.py
  codalab/lib/beam/ratarmount.py
  codalab/lib/upload_manager.py
  codalab/lib/zip_util.py
  codalab/worker/file_util.py
  docs/Externalization.md
  docs/Server-Setup.md
  requirements.txt
  tests/unit/lib/path_util_test.py
  tests/unit/lib/upload_manager_test.py
  tests/unit/worker/download_util_test.py
Labels: blob-storage, ready-to-merge

#3532 Get rid of the the bottom bar of the table
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: ready-to-merge

#3534 Fix table bottom hidden issue
  frontend/src/components/worksheets/items/TableItem/TableItem.js
Labels: ready-to-merge

#3516 Blob Storage download
  codalab/lib/download_manager.py
  codalab/worker/download_util.py
  codalab/worker/file_util.py
  tests/unit/server/upload_download_test.py
  tests/unit/worker/file_util_test.py
Labels: blob-storage, ready-to-merge

#3521 Show hidden fields for root
  codalab/lib/bundle_cli.py
  codalab/lib/worksheet_util.py
  codalab/rest/users.py
  tests/unit/rest/user_test.py
Labels: ready-to-merge

#3537 Warning for Adding Frontend Environment Variables
  docker_config/compose_files/docker-compose.yml
Labels: ready-to-merge

#3517 Add subset of Blob Storage E2E tests
  .github/workflows/test.yml
  codalab/lib/beam/ratarmount.py
  codalab/lib/path_util.py
  codalab/lib/upload_manager.py
Labels: blob-storage, ready-to-merge

#3553 Ensure CPU-only bundles don't have access to GPUs in slurm jobs
  codalab/worker/docker_utils.py
  codalab/worker/main.py
  codalab/worker_manager/slurm_batch_worker_manager.py
Labels: ready-to-merge

#3578 Add license to ratarmount code
  codalab/lib/beam/ratarmount.py
Labels: blob-storage, ready-to-merge

#3580 Make wide screen view the default for all users
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/constants.js
Labels: ready-to-merge
