Repository codalab/codalab-worksheets, pull requests merged in 2021-03, with the labels that each got.

#3315 Fix schema change detection on text field
  frontend/src/components/worksheets/items/SchemaItem/SchemaItem.js
Labels: bug, frontend, ready-to-merge

#3252 Force worker tags to be alphanumeric
  codalab/worker/main.py
Labels: ready-to-merge

#3323 Implement Image UI button & Fix after_sort_key bug
  frontend/src/__tests__/__snapshots__/Worksheet.test.js.snap
  frontend/src/components/worksheets/NewUpload/NewUpload.jsx
  frontend/src/components/worksheets/Worksheet/Worksheet.js
  frontend/src/components/worksheets/WorksheetItemList.js
  frontend/src/components/worksheets/items/ActionButtons.js
  frontend/src/components/worksheets/items/ImageEditor.js
  frontend/src/components/worksheets/items/ItemWrapper.js
  frontend/src/components/worksheets/items/TableItem/BundleRow.js
  frontend/src/util/worksheet_utils.js
Labels: ready-to-merge

#3304 Blob Storage: update requirements, add new args to codalab-service
  codalab_service.py
  docker_config/compose_files/docker-compose.yml
  docker_config/dockerfiles/Dockerfile.worker
  requirements.txt
Labels: blob-storage, ready-to-merge

#3300 Blob Storage: Add storage_type and is_dir columns
  alembic/versions/2021022419_azure_bundle_storage_type__e24a53ae9241.py
  codalab/common.py
  codalab/lib/path_util.py
  codalab/lib/upload_manager.py
  codalab/model/bundle_model.py
  codalab/model/tables.py
  codalab/objects/bundle.py
  codalab/rest/schemas.py
  docs/REST-API-Reference.md
  docs/Server-Setup.md
  tests/unit/lib/path_util_test.py
  tests/unit/lib/upload_manager_test.py
  tests/unit/objects/bundle_test.py
  tests/unit/server/bundle_manager/__init__.py
  tests/unit/server/bundle_manager/make_bundles_test.py
  tests/unit/server/bundle_manager/stage_bundles_test.py
  tests/unit/server/upload_download_test.py
Labels: blob-storage, ready-to-merge

#3354 Bump version to v0.5.43
  codalab/common.py
  docs/REST-API-Reference.md
  frontend/src/constants.js
  setup.py
Labels: ready-to-merge

#3295 Disallow editing metadata of frozen worksheets; enable unfreezing worksheets
  .github/workflows/test.yml
  codalab/lib/bundle_cli.py
  codalab/model/tables.py
  codalab/rest/worksheets.py
  docs/CLI-Reference.md
  tests/cli/test_cli.py
Labels: ready-to-merge

#3359 Upgrade urllib3 to 1.26.4
  requirements-server.txt
  requirements.txt
Labels: ready-to-merge

#3365 Add meta tag to home
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/HomePage.js
Labels: frontend

#3366 Make username clickable
  frontend/src/components/NavBar.js
Labels: frontend, ready-to-merge

#3341 GCP worker manager
  codalab/worker_manager/gcp_batch_worker_manager.py
  codalab/worker_manager/main.py
  requirements-server.txt
Labels: ready-to-merge

#3355 Blob Storage: Use new forked version of ratarmount
  requirements.txt
Labels: blob-storage, ready-to-merge

#3306 Blob Storage: Update MultiDiskBundleStore to use blob storage
  codalab/lib/bundle_store.py
  codalab/lib/codalab_manager.py
  codalab/model/bundle_model.py
Labels: blob-storage
